# Generated by Django 5.0.2 on 2025-04-23 22:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Discord')),
                ('rank', models.CharField(max_length=100, verbose_name='Ranga')),
                ('department', models.CharField(choices=[('Security', 'Ochrona'), ('Management', 'Zarząd'), ('Food', 'Gastronomia')], max_length=50, verbose_name='Dział')),
                ('base_weekly_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Podstawowa wypłata tygodniowa')),
                ('overtime_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stawka za nadgodziny')),
                ('panel_role', models.CharField(choices=[('Admin', 'Administrator'), ('Manager', 'Manager'), ('Employee', 'Pracownik')], default='Employee', max_length=20, verbose_name='Rola w panelu')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.profile', verbose_name='Przełożony')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField(verbose_name='Początek okresu')),
                ('period_end_date', models.DateField(verbose_name='Koniec okresu')),
                ('approved_hours', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Zatwierdzone godziny')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Godziny nadliczbowe')),
                ('base_pay_earned', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wynagrodzenie podstawowe')),
                ('overtime_pay_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wynagrodzenie za nadgodziny')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Premie')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Potrącenia')),
                ('total_pay', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suma do wypłaty')),
                ('status', models.CharField(choices=[('Calculated', 'Obliczona'), ('Paid', 'Wypłacona'), ('Error', 'Błąd')], default='Calculated', max_length=20, verbose_name='Status')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Data obliczenia')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data wypłaty')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='core.profile', verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Wypłata',
                'verbose_name_plural': 'Wypłaty',
                'ordering': ['-period_start_date'],
                'indexes': [models.Index(fields=['employee', 'period_start_date'], name='core_payout_employe_987743_idx'), models.Index(fields=['status'], name='core_payout_status_cdedd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Czas rozpoczęcia')),
                ('end_time', models.DateTimeField(verbose_name='Czas zakończenia')),
                ('duration', models.DurationField(editable=False, verbose_name='Czas trwania')),
                ('status', models.CharField(choices=[('Pending', 'Oczekujący'), ('Approved', 'Zaakceptowany'), ('Rejected', 'Odrzucony')], default='Pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zatwierdzenia')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('week_number', models.IntegerField(editable=False, verbose_name='Numer tygodnia')),
                ('year', models.IntegerField(editable=False, verbose_name='Rok')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries', to=settings.AUTH_USER_MODEL, verbose_name='Zatwierdzone przez')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.profile', verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Wpis czasu pracy',
                'verbose_name_plural': 'Wpisy czasu pracy',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['employee', 'week_number', 'year'], name='core_timeen_employe_793240_idx'), models.Index(fields=['status'], name='core_timeen_status_7ff1b5_idx')],
            },
        ),
    ]
