# Generated by Django 5.0.2 on 2025-04-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas zakończenia'),
        ),
    ]
