# Generated by Django 5.0.2 on 2025-04-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_timeentry_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='duration',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='Czas trwania'),
        ),
    ]
